urls.py
"""from django.contrib import admin
from django.urls import path,include
from . import views
#namespace
app_name='home'
urlpatterns = [
    path('',views.index,name='index'),
    path('signup/',views.signup,name='signup'),
    path('confidence/',views.confidence,name='confidence'),
    path('academics/',views.academics,name='academics'),
    path('fitness/',views.fitness,name='fitness'),
    path('personality_development/',views.personality_development,name='personality_development'),
    path('home/',views.home,name='home'),
    path('login/',views.loginUser,name='login'),
    path('questionnare/',views.questionnare,name='questionnare'),
    path('logout/',views.logoutUser,name='logout'),
    path('attempt/',views.Attempt,name='attempt'),
    path('emailsent/',views.emailsent,name='emailsent'),
    path('addon/',views.addon,name='addon'),
    path('feedback/',views.feedback,name='feedback'),
    path('confidence/save_confi',views.save_confi,name='save_confi'),]
    """
"""api3 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path,include
from . import views
#namespace
app_name='home'
urlpatterns = [
    path('',views.index,name='index'),
    path('signup/',views.signup,name='signup'),
    path('confidence/',views.confidence,name='confidence'),
    path('academics/',views.academics,name='academics'),
    path('fitness/',views.fitness,name='fitness'),
    path('personality_development/',views.personality_development,name='personality_development'),
    path('home/',views.home,name='home'),
    path('login/',views.loginUser,name='login'),
    path('questionnare/',views.questionnare,name='questionnare'),
    path('logout/',views.logoutUser,name='logout'),
    path('attempt/',views.Attempt,name='attempt'),
    path('addon/',views.addon,name='addon'),
    path('feedback/',views.feedback,name='feedback'),
    path('report/',views.report,name='report'),
    path('barg/',views.barg,name='barg'),
    path('certificate/',views.certificate,name='certificate'),
	path('mainpost/',views.getvalues,name='getvalues'),
    path('piechart/',views.piec,name='piec'),
    ]


templates/home/academics.html
{% extends 'home/base.html' %} {% block title %} ACADEMICS {% endblock %} {% block content %}
<body >
    <form method="POST" action="/home/mainpost">
    {% csrf_token %}
<div class = "container-fluid " class='active' >

    <div class="jumbotronaca">
     <h3>Academics Quiz I</h3>
    

      {% for quest in q %}
      <fieldset>
       <h4>
          <b>{{ forloop.counter }} . {{quest.question}}</b>
          <br>
          <br>
          <input hidden='true' value=''>
          <input type="radio"  id='rad'  value="{{quest.aw}}" name='{{quest.id}}' > {{quest.a}}<br>
          <input type="radio"  id='rad' value="{{quest.bw}}" name='{{quest.id}}'> {{quest.b}}<br>
          <input type="radio"  id='rad' value="{{quest.cw}}" name='{{quest.id}}'> {{quest.c}}<br>
          <input type="radio"  id='rad' value="{{quest.dw}}" name='{{quest.id}}'> {{quest.d}}<br>
          <br>
        </h4>
        
      </fieldset>
       {% endfor %}
       <input type='hidden' name='mainsum' id='mainsum' value='0'/>

      <input type='hidden' name='nexturl' id='mainsum' value='home:personality_development' />       
       <button class="btn" onclick='calculate()' id='nextbtn'>NEXT</button>
	   <p id='sum' hidden onclick='calculate()'>GET SUM</p> 
     </form>

   	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
	<script>
   

	
	function calculate ()
	{
	var sum2=parseInt(0);
	var x=document.querySelectorAll("[id='rad']");
	for(i=0 ; i< x.length ; i++)
	{
	
	if(x[i].checked)
		{
		console.log(x[i].value);
		sum2 = sum2+ parseInt(x[i].value);		
		}
	
	}
	
	//alert(sum2);
	document.getElementById('sum').innerHTML=sum2;
	document.getElementById('mainsum').value=sum2;
	}
	8
   </script>
    
    
    </div>
    </div>


{% endblock %}

templates/home/addon.html
{% extends 'home/base.html' %} {% block title %} HOME {% endblock %} {% block content %}


<form method="POST" action="/home/addon/">
{% csrf_token %}
<div class = "container-fluid" >

<div class="jumbotron addon" >
            <div class="container" >
            <h1>CO-CURRICULAM ACTIVITIES</h1>
            <hr>
            <!--<label for="TITLE"><b>Title</b></label>
            <textarea input type="text" placeholder=" " name="title" required rows='1' cols="10"></textarea>
            <br>-->
          
            <label for="content"><b>Tell us about yourself </b></label>
            <textarea input type="textarea" placeholder=" " name="content"  rows='8' cols="200"></textarea>
            <br>
            <br>
          
            <label for="content"><b>Tell about your Certifications </b></label>
            
            
            <textarea input type="textarea" placeholder=" " name="content"  rows='8' cols="100"></textarea>
            <br>
            <br>

            <label for="content"><b>Tell us about your Internships</b></label>
          
            <textarea input type="textarea" placeholder=" " name="content"  rows='8' cols="100"></textarea>
            <br>
            <br>
            <label for="content"><b>Tell us about Hobbies & Interests</b></label>
           
            <textarea input type="textarea" placeholder=" " name="content"  rows='8' cols="100"></textarea>
            <br>
            <br>
            <label for="content"><b>Tell us about your Future goals</b></label>
            
            <textarea input type="textarea" placeholder=" " name="content"  rows='8' cols="100"></textarea>
            <br>
            <br>

            <hr>
<form action='barg' method='POST'>
      <button hidden type='submit'  >GENERATE REPORT</button>
      <a href='http://127.0.0.1:8000/home/report/'> GENERATE REPORT</a>
      </form>        </div>

    </form>

</div>
</div>
{% endblock %}

templates/home/base.html
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
     <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'home/css/base_style.css' %}" rel="stylesheet ">
        <link href="https://fonts.googleapis.com/css?family=Be+Vietnam&display=swap" rel="stylesheet">


</head>

<body class="active">
    <form method="POST" action="/home/mainpost/ ">
    {% csrf_token %}
    <div class="header" ></div>
    <ul>
      <li> <a href="{% url 'home:home'%} ">{% load static %} <img src="{% static "home/images/LOGO.PNG" %} " alt="logo " height="50 " width="120 "/></a></li>
      <li><a class="navfont" href="{% url 'home:confidence'%}  ">Confidence</a></li>
      <li><a class="navfont"  href="{% url 'home:fitness'%}  ">Fitness</a></li>
      <li><a class="navfont"  href="{% url 'home:academics'%}  ">Academics</a></li>
      <li><a class="navfont"  href="{% url 'home:personality_development'%}  ">Personality Development</a></li>
      <li><a class="navfont"  href="{% url 'home:addon'%}  ">Add On</a></li>

      <li>{% load static %}<a href="{% url 'home:feedback'%} "> <img src="{% static "home/images/F.PNG" %} " alt="feedback " height="70 " width="90 "></a></li>
      <li> {% load static %} <a href="{% url 'home:login'%} "><img src="{% static "home/images/L.PNG" %} " alt="logout " height="70 " width="80 " /></a> </li>
    </ul>
    {% block content %}{% endblock %}
</body>
</html>

templates/home/index.html
<!DOCTYPE html>
<html>

<head>
    <title>Home</title>
</head>

<body>
    <!doctype html>
    <html lang="en">

    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="<link href=" https://fonts.googleapis.com/css?family=Saira+Extra+Condensed&display=swap " rel="stylesheet ">

    <title>Inklin'</title>
  </head>
  <body>
  <!DOCTYPE html>
<html>
<head>
<style>
body {
  font-size: 28px;
}

ul {
  list-style-type: none;
  margin: 5;
  padding: 5;
  overflow: hidden;
  background-color: #111;
  position: -webkit-sticky; /* Safari */
  position: sticky;
  top: 0;
}

li {
  float: left;
  padding: 16px 16px;

}

li a {
  display: block;
  color: white;
  text-align: center;
  padding: 16px 16px;
  text-decoration: none;
  font-size: 20px;
}

li a:hover {
  background-color: #D3F6F6;

}

.active {
  background-color: #111;
}
.navfont
{
font-family: 'Saira Extra Condensed', sans-serif;
}
</style>
</head>
<body>

<div class="header ">
 
</div>

<ul>
  <li><a class="navfont " href="{% url 'home:signup' %} ">Signup</a></li>
  <li><a class="navfont "  href="{% url 'home:login' %} ">Login</a></li>
  <li><a class="navfont "  href="{% url 'home:logout' %} ">Logout</a></li>

</ul>
<div class="card ">
  {% for quest in q %}
  <div class="card-header "><h3>{{quest.qid}} . {{quest.questions}}</h3></div>
  <div class="card-body "><p>{{quest.a}}</p></div>
  <div class="card-body "><p>{{quest.b}}</p></div>
  <div class="card-body "><p>{{quest.c}}</p></div>
  <div class="card-body "><p>{{quest.d}}</p></div>
  <div class="card-footer "><h5> you are currently giving test for {{quest.domain}}</h5></div>
  <br>
  <br>
  {% endfor %}
</div>
</body>
</html>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js " integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo " crossorigin="anonymous "></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js " integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1 " crossorigin="anonymous "></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js " integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM " crossorigin="anonymous "></script>
  </body>
</html>


</body>
</html>

templates/home/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Login Page</title>
    <style>
        /* Basics */
        
        html,
        body {
            padding: 0;
            margin: 0;
            width: 100%;
            height: 100%;
            font-family: "Helvetica Neue", Helvetica, sans-serif;
            background: #FFFFFF;
        }
        
        .logincontent {
            position: fixed;
            width: 350px;
            height: 300px;
            top: 50%;
            left: 50%;
            margin-top: -150px;
            margin-left: -175px;
            background: #07A8C3;
            padding-top: 10px;
        }
        
        .loginheading {
            border-bottom: solid 1px #ECF2F5;
            padding-left: 18px;
            padding-bottom: 10px;
            color: #ffffff;
            font-size: 20px;
            font-weight: bold;
            font-family: sans-serif;
        }
        
        label {
            color: #ffffff;
            display: inline-block;
            margin-left: 18px;
            padding-top: 10px;
            font-size: 15px;
        }
        
        input[type=text],
        input[type=password] {
            font-size: 14px;
            padding-left: 10px;
            margin: 10px;
            margin-top: 12px;
            margin-left: 18px;
            width: 300px;
            height: 35px;
            border: 1px solid #ccc;
            border-radius: 2px;
            box-shadow: inset 0 1.5px 3px rgba(190, 190, 190, .4), 0 0 0 5px #f5f5f5;
            font-size: 14px;
        }
        
        input[type=checkbox] {
            margin-left: 18px;
            margin-top: 30px;
        }
        
        .loginremember {
            background: #ECF2F5;
            height: 70px;
            margin-top: 20px;
        }
        
        .check {
            font-family: sans-serif;
            position: relative;
            top: -2px;
            margin-left: 2px;
            padding: 0px;
            font-size: 12px;
            color: #321;
        }
        
        .loginbtn {
            float: right;
            margin-right: 20px;
            margin-top: 20px;
            padding: 6px 20px;
            font-size: 14px;
            font-weight: bold;
            color: #fff;
            background-color: #07A8C3;
            background-image: -webkit-gradient(linear, left top, left bottom, from(#07A8C3), to(#6EE4E8));
            background-image: -moz-linear-gradient(top left 90deg, #07A8C3 0%, #6EE4E8 100%);
            background-image: linear-gradient(top left 90deg, #07A8C3 0%, #6EE4E8 100%);
            border-radius: 30px;
            border: 1px solid #07A8C3;
            cursor: pointer;
        }
        
        .loginbtn:hover {
            background-image: -webkit-gradient(linear, left top, left bottom, from(#b6e2ff), to(#6ec2e8));
            background-image: -moz-linear-gradient(top left 90deg, #b6e2ff 0%, #6ec2e8 100%);
            background-image: linear-gradient(top left 90deg, #b6e2ff 0%, #6ec2e8 100%);
        }
        
        p {
            text-align: center;
        }
    </style>
</head>

<body>
    <form method="POST" action="/home/login/">
        {% csrf_token %}
        <div class="logincontent">
            <div class="loginheading">
                Login
            </div>
            <label for="username">
                username:</label>
            <input type="text" name="username" />
            <label for="txtPassword">
                Password:</label>
            <input type="password" name="password" />
            <div class="loginremember">
                <input type="checkbox" id="chbRemember" name="chbRemember" /><label class="check" for="chbRemember">Remember me next time</label>
                <a href="home.html"><input type="submit" class="loginbtn" value="Login" id="btnSubmit" /></a>
                <br>
                <br>

                <p>Don't have an account? <a href="{%url 'home:signup' %}">Sign up</a></p>

            </div>
        </div>

    </form>
</body>

</html> 

templates/home/report.html
<!DOCTYPE html>
<title>REPORT</title>
<link href="https://fonts.googleapis.com/css?family=Playfair+Display&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">

<style>
    body {
        display: grid;
        grid-template-areas: "header header header" "nav article ads" "footer footer footer";
        grid-template-rows: 60px 1fr 60px;
        grid-template-columns: 20% 1fr 15%;
        grid-gap: 10px;
        height: 100vh;
        margin: 0;
    }
    
    #pageHeader {
        grid-area: header;
        font-family: 'Playfair Display', serif;
        color: white;
        text-align: center;
    }
    
    #pageFooter {
        grid-area: footer;
        font-family: 'Playfair Display', serif;
        color: white;
        text-align: center;
    }
    
    #mainArticle {
        grid-area: article;
    }
    
    #mainNav {
        grid-area: nav;
    }
    
    #siteAds {
        width: 50%;
        grid-area: ads;
    }
    
    .button {
        background-color: #464159;
        /* Green */
        border: double;
        color: white;
        align-self: left;
        align: left;
        text-decoration-color: silver;
        text-align: left;
        text-decoration: none;
        padding: 8px;
        margin: -10px;
        font-family: 'Playfair Display', serif;
        color: white;
        font-size: 16px;
    }
    
    div {
        padding: 20px;
        background: #afeeee;
    }
    
    nav {
        padding: 20px;
        background: #8bbabb;
    }
    
    article {
        padding: 20px;
        background: white;
    }
    
    footer {
        padding: 20px;
        background: #6c7b95;
    }
    
    header {
        padding: 20px;
        background: #464159;
    }
    
    nav ul {
        list-style-type: none;
        margin: 0;
        font-family: 'Playfair Display', serif;
        padding: 0;
    }
    
    nav ul a {
        color: #464159;
        font-family: 'Playfair Display', serif;
        text-decoration: none;
    }
    
    p {
        color: #146ca4;
        font-family: 'Playfair Display', serif;
        text-align: center;
        font-size: 18px;
    }
    
    h1 {
        font-family: 'Roboto', sans-serif;
        text-align: center;
        font-size: 6-px;
        background-color: mediumspringgreen;
        font-size: 40px;
    }
    
    #pageHeader {
        font-size: 20px;
    }
    
    body {
        background-color: #E6FFEE;
    }
</style>

<body>
    <header id="pageHeader"><b> INKLIN' </b></header>




    <article id="mainArticle">

        <p>

            <h1 class="myheading"> STUDENT DEVELOPMENT </h1>
            <p>Student Development Theory refers to the body of educational psychology that theorizes how students gain knowledge in post-secondary educational environments.</p>




            <h1 class="myheading"> CONFIDENCE</h1>
            <center> {% load static %}<img border="self" src="{% static " home/images/self-confidence.jpg " %} " alt="self confidence face" height="400" width="500">
            </center>

            <p>Confidence can be described as a belief in oneself and the ability to succeed. Being confident is to possess a realistic sense of one’s capacity and feel secure in that knowledge.<br>
                <br> Striking a healthy balance between too much and too little confidence can be challenging. Too much confidence can come off as cocky and arrogant. Overestimating one’s abilities might also lead to pitfalls, such as failing to complete
                projects on time.<br>
                <br> But too little confidence can prevent people from taking risks and seizing opportunities—in school, at work, or in their social life.<br>
                <br>
                <!--<center><img   src="C:\Users\hp\Desktop\sdlprojectmain\REPORT\IMAGES\R.png" alt="self confidence face" height="400" width="500></center>
</center>-->
                {% load static %}<img border="self" src="{% static " home/images/R.png " %} " alt="self confidence face" height="400" width="500"><br>
                <br> Projecting just enough confidence helps people gain credibility, make a strong first impression, deal with pressure, and tackle personal and professional challenges.
                <BR>
                <BR> The best way to ensure a balanced sense of confidence is to assess oneself realistically. Confidence that’s based firmly on what is known may not only be a better guide than exaggerated certainty; studies suggest it’s also more likely
                to earn the faith of others.<br>
                <p>


                    <br>
                </p>


                <h1 class="myheading"> FITNESS</h1>
                <p>
                    Fitness is a state of health and well-being and, more specifically, the ability to perform aspects of sports, occupations and daily activities. Physical fitness is generally achieved through proper nutrition, moderate-vigorous physical exercise, and sufficient
                    rest.
                    <br></p>



                <center> {% load static %}<img border="self" src="{% static " home/images/ff.jpg " %} " alt="self confidence face" height="400" width="500">
                </center>

                <p>Regular exercise and physical activity increase muscle strength, bone density, flexibility, and stability. Physical fitness can reduce your risk for and resilience to accidental injuries, especially as you get older. </p>

                <center> {% load static %}<img border="self" src="{% static " home/images/f.jpg " %} " alt="self confidence face" height="400" width="500">
                </center>




                <p>Making healthy choices, such as engaging in regular physical activity, can reduce your risk for many health issues and complications that can result in expensive medical care.</p>


                <h1 class="myheading"> ACADEMICS</h1>
                <p>
                    Academics is the quality of your approach for learning throughout your life and inculcating good teachings actually can be stated as qualities academically sound person.</p>



                <p>one of the important faces of academics is discipline which has many virtues like being focused, staying healthy and also avoiding problems.</p>

                <center> {% load static %}<img border="self" src="{% static " home/images/c.jpg " %} " alt="self confidence face" height="400" width="500">
                </center>

                <p>Learning process about any domain should come from within and only then it has some productive outputs. In short, learning must be a self driven process. However tough the process gets going,you should stick your goals as perseverance
                    is major key to success.</p>


            </p>



            <h1 class="myheading">PERSONALITY DEVELOPMENT </h1>
            <p>

                Personality development helps you develop an impressive personality and makes you stand apart from the rest.</p>

            <p>Personality development also plays an essential role in improving one's communication skills.</p>
            <br>
            <center> {% load static %}<img border="self" src="{% static " home/images/personalityDevelopment.jpg " %}" alt="self confidence face" height="400" width="500">
            </center>


            <p>
                Individuals ought to master the art of expressing their thoughts and feelings in the most desired way.</p>

            <p> Personality represents the people how you are. It is not just looks that are important and that define who you are. </p>
            <center> {% load static %}<img border="self" src="{% static " home/images/personality2.jpg " %}" alt="self confidence face" height="400" width="500">
            </center>


            <p>The personality of an individual is determined by his/her appearance, behavior, attitude, education, values and some more varying characteristics.</p>

            <p>Personality defines who you are and how you respond to various situations. It is essential to focus on the personality, which matters the most.</p>


        </p>



        <h1 class="myheading"> ADD-ON </h1>
        <p>
            When it comes to improving your mental health, there are few better remedies than picking up a healthy hobby. Hobbies can get your mind active, and get you social—but the real benefit to most people is the boost to overall mental wellness.</p>


        <p>For professional as well as individual growth, people today have resorted to gaining deeper knowledge in their respective fields. Similar is the case with the IT industry. Furthermore, IT certifications help in keeping up with the rapidly evolving
            industry. </p>
        <p>An organization that has skilled and certified human resources not only does better at providing quality deliverables, but also bolsters the company’s reputation in attracting and building new business.</p>
        <center> {% load static %}<img border="self" src="{% static " home/images/addOn.jpeg " %}" alt="self confidence face" height="400" width="500">
        </center>

        <p>IT professionals through additional certifications, can leverage upon their skills in terms of interesting project opportunities and client acceptance.An organization with certified personnel reassures them of their project being in competent
            hands.An internship enables you to gain first-hand exposure of working in the real world.</p>

        <p>It also allows students to harness the skill, knowledge, and theoretical practice they learnt in university.</p>

        <p>You can acquire endless amounts of education in your life, however, that knowledge doesn't always translate to the working life. Doing an internship exposes you to new people in a more controlled and stable environment.
        </p>







    </article>
    <nav id="mainNav">
        <ul>
            <br>
            <b>
        <li><a  href="#">CONFIDENCE</a></li><br>

        <li><a href="#">FITNESS</a></li><br>
        <li><a href="#">ACADEMICS</a></li><br>
        <li><a href="#">PERSONALITY DEVELOPMENT</a></li><br>
        <li><a href="#">ADD ON</a></li>
        <br>
        <br>
<button type='submit'><a href={% url 'home:certificate' %}>GENERATE CERTIFICATE</a></button>
<button type='submit'><a href={% url 'home:barg' %}>GENERATE BARGRAPH</a></button>
<button type='submit'><a href={% url 'home:piec' %}>GENERATE PIECHART</a></button>


        <br>
        <br>
       <li>
                       
      </b>
        </ul>
    </nav>
    <!--<div id="siteAds">Ads</div>-->
    <footer id="pageFooter">HELPING.YOU.NUTURE</footer>
</body>

templates/home/signup.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Login Page</title>
    <style>
        /* Basics */
        
        html,
        body {
            padding: 0;
            margin: 0;
            width: 100%;
            height: 100%;
            font-family: "Helvetica Neue", Helvetica, sans-serif;
            background: #FFFFFF;
        }
        
        .logincontent {
            position: fixed;
            width: 350px;
            height: 500px;
            top: 50%;
            left: 50%;
            margin-top: -300px;
            margin-left: -175px;
            background: #07A8C3;
            padding-top: 10px;
        }
        
        .loginheading {
            border-bottom: solid 1px #ECF2F5;
            padding-left: 18px;
            padding-bottom: 10px;
            color: #ffffff;
            font-size: 20px;
            font-weight: bold;
            font-family: sans-serif;
        }
        
        label {
            color: #ffffff;
            display: inline-block;
            margin-left: 18px;
            padding-top: 10px;
            font-size: 15px;
        }
        
        input[type=text],
        input[type=email],
        input[type=password] {
            font-size: 14px;
            padding-left: 10px;
            margin: 10px;
            margin-top: 12px;
            margin-left: 18px;
            width: 300px;
            height: 35px;
            border: 1px solid #ccc;
            border-radius: 2px;
            box-shadow: inset 0 1.5px 3px rgba(190, 190, 190, .4), 0 0 0 5px #f5f5f5;
            font-size: 14px;
        }
        
        input[type=checkbox] {
            margin-left: 18px;
            margin-top: 30px;
        }
        
        .loginremember {
            background: #ECF2F5;
            height: 70px;
            margin-top: 20px;
        }
        
        .check {
            font-family: sans-serif;
            position: relative;
            top: -2px;
            margin-left: 2px;
            padding: 0px;
            font-size: 12px;
            color: #321;
        }
        
        .loginbtn {
            float: right;
            margin-right: 20px;
            margin-top: 20px;
            padding: 6px 20px;
            font-size: 14px;
            font-weight: bold;
            color: #fff;
            background-color: #07A8C3;
            background-image: -webkit-gradient(linear, left top, left bottom, from(#07A8C3), to(#6EE4E8));
            background-image: -moz-linear-gradient(top left 90deg, #07A8C3 0%, #6EE4E8 100%);
            background-image: linear-gradient(top left 90deg, #07A8C3 0%, #6EE4E8 100%);
            border-radius: 30px;
            border: 1px solid #07A8C3;
            cursor: pointer;
        }
        
        .loginbtn:hover {
            background-image: -webkit-gradient(linear, left top, left bottom, from(#b6e2ff), to(#6ec2e8));
            background-image: -moz-linear-gradient(top left 90deg, #b6e2ff 0%, #6ec2e8 100%);
            background-image: linear-gradient(top left 90deg, #b6e2ff 0%, #6ec2e8 100%);
        }
        
        p {
            text-align: center;
        }
    </style>
</head>

<body>
    <form method="POST" action="/home/signup/">
    {{error}}
        {% csrf_token %}
        <div class="logincontent">
            <div class="loginheading">
                SIGN UP
            </div>

            <label for="username"><b>username</b></label>
            <input type="text" placeholder="Enter username" name="username" required>
            <label for="fname"><b>first_name</b></label>
            <input type="text" placeholder="Enter first_name" name="fname" required>
            <label for="lname"><b>last_name</b></label>
            <input type="text" placeholder="Enter last_name" name="lname" required>

            <label for="email"><b>email</b></label>
            <br>
            <input type="email" placeholder="Enter Email" name="email" required>
            <br>
            <label for="txtPassword"><b>password</b></label>
            <input type="password" placeholder="Enter Password" name="password" required>
            <div class="loginremember">
                <a href="home.html"><input type="submit" class="loginbtn" value="Sign Up" id="btnSubmit" /></a>
                <br>
                <br>
                <br>

                <p>Already have an account? <a href="{% url 'home:login'%}">Login</a>.</p>

            </div>

        </div>
        </div>

    </form>
</body>

</html>